global:
  scrape_interval: 15s

scrape_configs:
  # RabbitMQ metrics
  - job_name: "rabbitmq"
    static_configs:
      - targets: ["rabbitmq:15692"]

  # Your Node.js services
  - job_name: "user-service"
    static_configs:
      - targets: ["user-service:3001"]

  - job_name: "notification-service"
    static_configs:
      - targets: ["notification-service:3002"]

  - job_name: "recommendation-service"
    static_configs:
      - targets: ["recommendation-service:3003"]
